# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tandaaccount',
            old_name='username',
            new_name='email',
        ),
    ]
