# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_auto_20160422_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='customURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
